apiVersion: v1
kind: Service
metadata:
  name: flask-svc
spec:
  type: NodePort
  selector:
    app: flask-app        
  ports:
    - name: http
      port: 8080          # service-port
      targetPort: 8080    # container-port
  
